### ISSUE TITLE
i think the toe beakes are swapped

### ISSUE THREAD

**Issue by mherweg** [FGMEMBERS/A380#1]

**Comment by FGDATA** [comment]
is it Really?

Recently, Ludovic Brenta committed a change in the engines that changed the brakes .I got that change when rebasing, and it is here: 9d2fbe9a16ef751ec41548917955a30bc1d00de5

Now, I wonder, which one is correct, the current or the previous status. 
Do you want to help me verify, @mherweg 

Is the current version OK?
or is the version as on here: 

```
  git checkout -b test 1081c1
```

Correct.

Let me know. and if the previous status is more correct, I will revert the changes applied by L. Brenta on this)

**Comment by mherweg** [comment]
On 05.09.2015 19:06, FGDATA wrote:

> is it Really?

not anymore. my version was a bit older.
with the latest Version
toe breakes are good now, and i think it also taxies better now.

**Comment by jan-hudec** [comment]
@mherweg, so I suppose I may mark this as closed, right?

**Comment by FGDATA** [comment]
Thanks For looking at this @mherweg
